library/book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('books/', views.book_list, name='book_list'),
    path('books/<int:id>', views.book_detail, name='book_detail'),
    path('search/', views.search_books, name='search_books'),
    path('books/add/', views.add_book, name='add_book'),
    path('books/<int:id>/edit/', views.edit_book, name='edit_book'),
    path('books/<int:id>/delete/', views.delete_book, name='delete_book'),
    path('filter', views.filter_books, name='filter_books'),
    path('delete_filtered', views.delete_filtered_books, name='delete_filtered_books'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls', namespace='library')),
]

library/book/models.py
from django.db import models
from django.utils import timezone


class Author(models.Model):
    name = models.CharField(max_length=250)

    def __str__ (self):
        return self.name


class Price(models.Model):
    price = models.BigIntegerField(max_length=None)

    def __str__ (self):
        return str(self.price)


class Book(models.Model):
    class Category(models.TextChoices):
        Biography = 'B', 'Biography'
        Childrens_fiction = 'C', 'Childrens fiction'
        Fantasy  = 'F', 'Fantasy'
        Horror = 'H', 'Horror'
        Inspirational  = 'I', 'Inspirational'
        Mystery = 'M', 'Mystery'
        Romance = 'R', 'Romance'
        Young_adult = 'V', 'Young adult'


    #Data field
    name = models.CharField(max_length=250)

    #Relation field
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE, 
        null=True,
        related_name='author_books',
    )
    price = models.ForeignKey(
        Price,
        on_delete=models.CASCADE, 
        null=True,
        related_name='book_price',
    )

    #Date field
    published_at = models.DateTimeField(auto_now_add=True)

    #Choice field
    category = models.CharField(
        max_length=2, 
        choices=Category.choices, 
        default=Category.Biography
    )

    class  Meta:
        ordering = [
            '-published_at',
        ]
        indexes = [
            models.Index(fields=['-published_at',]),
        ]


    def __str__ (self):
        return self.name

library/book/forms.py
from django import forms
from .models import *

class AddBookForm(forms.ModelForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        label='Author',
        required=False,
        empty_label='Select an author or add new'
    )
    new_author = forms.CharField(label='New Author', max_length=250, required=False)

    price = forms.ModelChoiceField(
        queryset=Price.objects.all(),
        label='Price',
        required=False,
        empty_label='Select a price or add new'
    )
    new_price = forms.IntegerField(label='New Price', max_value=None, required=False)


    class Meta:
        model = Book
        fields = ['name', 'author', 'new_author', 'price', 'new_price', 'category']

    def clean(self):
        cleaned_data = super().clean()
        author = cleaned_data.get("author")
        new_author = cleaned_data.get("new_author")
        price = cleaned_data.get("price")
        new_price = cleaned_data.get("new_price")

        if not author and not new_author:
            raise forms.ValidationError("Please select an existing author or enter a new author name.")

        if author and new_author:
            raise forms.ValidationError("Please either select an existing author or enter a new author, not both.")
        
        if not price and not new_price:
            raise forms.ValidationError("Please select an existing price or enter a new price.")
        
        if price and new_price:
            raise forms.ValidationError("Please either select an existing price or enter a new price, not both.")

        return cleaned_data
    

class EditBookForm(forms.ModelForm):
    author_name = forms.CharField(label='Author Name', max_length=250)
    price_amount = forms.CharField(label='Price', max_length=None)

    class Meta:
        model = Book
        fields = ['name', 'author_name', 'price_amount', 'category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.fields['name'].initial = self.instance.name 
            self.fields['author_name'].initial = self.instance.author.name if self.instance.author else ''
            self.fields['price_amount'].initial = self.instance.price.price if self.instance.price else ''
            self.fields['category'].initial = self.instance.category

library/book/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import AddBookForm, EditBookForm

def book_list(request):
    books = Book.objects.all()
    return render(request, 'book/list.html', {'books' : books})


def book_detail(request, id):
    book = get_object_or_404(Book, id = id)
    return render(request, 'book/detail.html', {'book' : book})


def search_books(request):
    query = request.GET.get('query', None)

    if query:

        book_name_search = Book.objects.filter(name__icontains= query)
        if book_name_search.exists():
            return render(request, 'book/list.html', {'books':book_name_search})
        
        try:
            author = Author.objects.get(name__icontains=query)
            auther_name_search = Book.objects.filter(author=author)
            return render(request, 'book/list.html', {'books':auther_name_search})
        except Author.DoesNotExist:
            return render(request, 'book/list.html', {'books':[]})

    return render(request, 'book/list.html', {'books':Book.objects.all()})



def add_book(request):
    context = {}
    if request.method == 'POST':
        form = AddBookForm(request.POST)
        if form.is_valid():
            author = form.cleaned_data['author']
            new_author_name = form.cleaned_data['new_author']
            price = form.cleaned_data['price']
            new_price_value = form.cleaned_data['new_price']

            if not author and new_author_name:
                author, created = Author.objects.get_or_create(name=new_author_name)

            if not price and new_price_value:
                price, created = Price.objects.get_or_create(price=new_price_value)

            book = form.save(commit=False)
            book.author = author
            book.price = price
            book.save()
    else:
        form = AddBookForm()

    context['form']=form
    return render(request, 'book/add.html', context)


def edit_book(request, id):
    context = {}
    book = get_object_or_404(Book, id=id)
    if request.method == 'POST':
        form = EditBookForm(request.POST, instance=book)
        if form.is_valid():
            new_author_name = form.cleaned_data['author_name']
            author, _ = Author.objects.get_or_create(name=new_author_name)

            new_price_value = form.cleaned_data['price_amount']
            price, _ = Price.objects.get_or_create(price=int(new_price_value))

            book.author = author
            book.price = price
            book.name = form.cleaned_data['name']
            book.category = form.cleaned_data['category']

            book.save()
            return HttpResponseRedirect("/books")
    else:
        form = EditBookForm(instance=book)

    context['form']=form
    context['book']=book
    return render(request, 'book/edit.html', context)
    


def delete_book(request, id):
    context = {}

    book = get_object_or_404(Book, id=id)

    if request.method == "POST":
        book.delete()
        return HttpResponseRedirect("/books")
        
    return render(request, 'book/delete.html', context)


def filter_books(request):
    price = request.GET.get('price', None)
    published_year = request.GET.get('date', None)
    books = Book.objects.all()

    if price:
        books = books.filter(price__price=int(price))
    if published_year:
        books = books.filter(published_at__year=int(published_year))

    context = {
        'books':books,
        'filtered_books': books.exists()
    }

    return render(request, 'book/list.html', context)


def delete_filtered_books(request):
    price = request.GET.get('price', None)
    published_year = request.GET.get('date', None)
    books = Book.objects.all()

    if price:
        books = books.filter(price__price=int(price))
    if published_year:
        books = books.filter(published_at__year=int(published_year))


    if request.method == "POST":
        books.delete()
        return HttpResponseRedirect("/books")
        

    return render(request, 'book/deletefilter.html', {'books':books})

library/book/templates/book/add.html
{% extends 'parent/base.html' %}
{% block title %}Add Book{% endblock %}
{% block head %}<h2>Add Book</h2>{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}
        
        <input type="submit" value="Submit">
    </form>
{% endblock %}

library/book/templates/book/delete.html
{% extends 'parent/base.html' %}
{% block title %}Add Book{% endblock %}
{% block head %}<h2>Delete Book</h2>{% endblock %}

{% block content %}
    <div class="main">
        <form method="POST">
            {% csrf_token %}
            Are you want to delete this item ?
            <input type="submit" value="Yes" />
            <a href="/books/">Cancel </a>
        </form>
    </div>
{% endblock %}

library/book/templates/book/deletefilter.html
{% extends 'parent/base.html' %}
{% block title %}Add Book{% endblock %}
{% block head %}<h2>Delete Book</h2>{% endblock %}

{% block content %}
<p>The following filtered books will be permanently deleted.</p>
    {% for book in books %}
        <li>{{ book.name }} - {{ book.author.name }} - {{ book.price.price }}</li>
        {% empty %}
        <li>No books found!</li>
    {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        Are you want to delete this items ?
        <input type="submit" value="Yes" />]
    </form>
    <a href="{% url 'book:book_list' %}">Return to the list of books</a>
{% endblock %}

library/book/templates/book/detail.html
{% extends 'parent/base.html' %}
{% block title %}Book Detail{% endblock %}
{% block head %}<h2>Book Detail</h2>{% endblock %}

{% block content %}
    <h3>{{ book }}</h3>
    <p>author:  {{ book.author }}</p>
    <p>genre:   {{ book.category }}</p>
    <p>price:   {{ book.price }}</p>
    <p>published at:    {{ book.published_at }}</p>
    <p>updated at:    {{ book.updated_at }}</p>
    <hr>
    <a href="{% url 'book:edit_book' book.id %}"><h3>edit</h3></a>
    <a href="{% url 'book:delete_book' book.id %}"><h3>delete</h3></a>
    
{% endblock %}

library/book/templates/book/edit.html
{% extends 'parent/base.html' %}
{% block title %}Add Book{% endblock %}
{% block head %}<h2>Edit Book: {{ form.instance.name }}</h2>{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}
        
        <button type="submit">Save Changes</button>
    </form>
{% endblock %}

library/book/templates/book/filter.html
{% extends 'parent/base.html' %}
{% block title %}Filtered Book List{% endblock %}
{% block head %}<h2>Filtered Book List</h2>{% endblock %}

{% block content %}
    <form method="get" action="{% url 'book:filter_books' %}">
        <div>
            <label for="price">Filter by Price:</label>
            <input type="number" id="price" name="price" placeholder="price"/>
        </div>
        <div>
            <label for="date">Filter by Publication Date (year):</label>
            <input type="number" id="date" name="date" placeholder="year"/>
        </div>
        <button type="submit">
            <i class="fa fa_filter"></i> Filter
        </button>
    </form>
    {% for book in books %}
        <h3>
            <a href="{% url 'book:book_detail' book.id %}">{{ book.name }}</a>
        </h3>
        <p>{{book.author}}</p>
        <hr>
    {% endfor %}


    <hr>
{% endblock %}

library/book/templates/book/list.html
{% extends 'parent/base.html' %}
{% block title %}Book List{% endblock %}
{% block head %}<h2>Book List</h2>{% endblock %}

{% block content %}
    <form method="get" action="{% url 'book:search_books' %}">
        <div>
            <label for="query">Search:</label>
            <input type="text" id="query" name="query" placeholder="Search by name or author" value="{{ request.GET.query }}"/>
        </div>
        <button type="submit">
            <i class="fa fa_search"></i> Search
        </button>
    </form>
    <form method="get" action="{% url 'book:filter_books' %}">
        <div>
            <label for="price">Filter by Price:</label>
            <input type="number" id="price" name="price" placeholder="price" step="1"/>
        </div>
        <div>
            <label for="date">Filter by Publication Date (year):</label>
            <input type="number" id="date" name="date" placeholder="year"/>
        </div>
        <button type="submit">
            <i class="fa fa_filter"></i> Filter
        </button>
    </form>
    {% for book in books %}
        <h3>
            <a href="{% url 'book:book_detail' book.id %}">{{ book.name }}</a>
        </h3>
        <p>{{book.author}}</p>
        <hr>
    {% endfor %}

    <hr>
    <h3><a href="{% url 'book:add_book' %}">add book</a></h3>
    {% if filtered_books %}
        <form method="get" action="{% url 'book:delete_filtered_books' %}">
            <input type="hidden" name="price" value="{{ request.GET.price }}">
            <input type="hidden" name="publication_date" value="{{ request.GET.publication_date }}">
            <button type="submit">delete filter books</button>
        </form>
    {% endif %}
{% endblock %}

library/book/templates/parent/base.html
{% load static %}
<!DOCTYPE html>
<html lang="'en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <h1>Library Management System</h1>
</head>

<body dir="ltr">
    <header>
        {% block head %}{% endblock %}
        
    </header>
    {% block content %}{% endblock %}

</body>
</html> 